In [2]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option('precision', 16)

In [3]:
import bz2
import pickle
import _pickle as cPickle

# Pickle a file and then compress it into a file with extension 
def compressed_pickle(title, data):
    with bz2.BZ2File(title + '.pbz2', 'w') as f: 
        cPickle.dump(data, f)

# Load any compressed pickle file
def decompress_pickle(file):
    data = bz2.BZ2File(file, 'rb')
    data = cPickle.load(data)
    return data

In [4]:
dataframe = pd.read_csv('TRAINING_24March2022_UNNORMED.csv')
dataframe

,Theta,Pitch,Duty Cycle,Fill Factor,Mode,Lambda,Transmission
0,5.0,0.00000050,0.4000000000000000,0.200000,0,0.00000170000,0.0000910340000000
1,5.0,0.00000050,0.4000000000000000,0.200000,0,0.00000169817,0.0001010460000000
2,5.0,0.00000050,0.4000000000000000,0.200000,0,0.00000169635,0.0001118810000000
3,5.0,0.00000050,0.4000000000000000,0.200000,0,0.00000169453,0.0001233320000000
4,5.0,0.00000050,0.4000000000000000,0.200000,0,0.00000169271,0.0001351560000000
...,...,...,...,...,...,...,...
2240395,11.0,0.00000151,0.4444439999999999,0.555556,1,0.00000131000,-0.0008086870000000
2240396,11.0,0.00000151,0.4444439999999999,0.555556,1,0.00000130000,-0.0008483639999999
2240397,11.0,0.00000151,0.4444439999999999,0.555556,1,0.00000130000,-0.0008844920000000
2240398,11.0,0.00000151,0.4444439999999999,0.555556,1,0.00000130000,-0.0009403480000000
2240399,11.0,0.00000151,0.4444439999999999,0.555556,1,0.00000130000,-0.0010073400000000

In [5]:
compressed_pickle('training_set_08May2022', dataframe)

In [7]:
columns_to_norm = ['Theta', 'Pitch', 'Duty Cycle', 'Fill Factor', 'Mode', 'Lambda']
dataframe[columns_to_norm] = dataframe[columns_to_norm].apply(lambda x: (x-x.min()) / (x.max() - x.min()))
dataframe

,Theta,Pitch,Duty Cycle,Fill Factor,Mode,Lambda,Transmission
0,0.0,0.0,0.0000000000000000,0.0000000000000000,0.0,1.0000000000000000,0.0000910340000000
1,0.0,0.0,0.0000000000000000,0.0000000000000000,0.0,0.9954249999999997,0.0001010460000000
2,0.0,0.0,0.0000000000000000,0.0000000000000000,0.0,0.9908750000000001,0.0001118810000000
3,0.0,0.0,0.0000000000000000,0.0000000000000000,0.0,0.9863250000000000,0.0001233320000000
4,0.0,0.0,0.0000000000000000,0.0000000000000000,0.0,0.9817749999999998,0.0001351560000000
...,...,...,...,...,...,...,...
2240395,0.4,1.0,0.1111099999999997,0.8888900000000002,1.0,0.0249999999999998,-0.0008086870000000
2240396,0.4,1.0,0.1111099999999997,0.8888900000000002,1.0,0.0000000000000000,-0.0008483639999999
2240397,0.4,1.0,0.1111099999999997,0.8888900000000002,1.0,0.0000000000000000,-0.0008844920000000
2240398,0.4,1.0,0.1111099999999997,0.8888900000000002,1.0,0.0000000000000000,-0.0009403480000000
2240399,0.4,1.0,0.1111099999999997,0.8888900000000002,1.0,0.0000000000000000,-0.0010073400000000

In [8]:
compressed_pickle('training_set_normalized_features_08May2022', dataframe)

In [26]:
training_set = decompress_pickle('training_set.pbz2')
training_set

,Theta,Pitch,Duty Cycle,Fill Factor,Mode,Lambda,Transmission
0,5.0,0.0000005,0.4,0.2,0,0.00000170000,0.000091034
1,5.0,0.0000005,0.4,0.2,0,0.00000169817,0.000101046
2,5.0,0.0000005,0.4,0.2,0,0.00000169635,0.000111881
3,5.0,0.0000005,0.4,0.2,0,0.00000169453,0.000123332
4,5.0,0.0000005,0.4,0.2,0,0.00000169271,0.000135156
...,...,...,...,...,...,...,...
2156395,20.0,0.0000015,0.8,0.6,1,0.00000130618,-0.012646500
2156396,20.0,0.0000015,0.8,0.6,1,0.00000130463,-0.012309600
2156397,20.0,0.0000015,0.8,0.6,1,0.00000130308,-0.012144300
2156398,20.0,0.0000015,0.8,0.6,1,0.00000130154,-0.011917400
2156399,20.0,0.0000015,0.8,0.6,1,0.00000130000,-0.011437500

In [27]:
columns_to_norm = ['Theta', 'Pitch', 'Duty Cycle', 'Fill Factor', 'Mode', 'Lambda']
training_set[columns_to_norm] = training_set[columns_to_norm].apply(lambda x: (x-x.min()) / (x.max() - x.min()))
training_set

,Theta,Pitch,Duty Cycle,Fill Factor,Mode,Lambda,Transmission
0,0.0,0.0,0.0,0.0,0.0,1.0000000000000000,0.000091034
1,0.0,0.0,0.0,0.0,0.0,0.9954249999999997,0.000101046
2,0.0,0.0,0.0,0.0,0.0,0.9908750000000001,0.000111881
3,0.0,0.0,0.0,0.0,0.0,0.9863250000000000,0.000123332
4,0.0,0.0,0.0,0.0,0.0,0.9817749999999998,0.000135156
...,...,...,...,...,...,...,...
2156395,1.0,1.0,1.0,1.0,1.0,0.0154499999999998,-0.012646500
2156396,1.0,1.0,1.0,1.0,1.0,0.0115749999999998,-0.012309600
2156397,1.0,1.0,1.0,1.0,1.0,0.0076999999999997,-0.012144300
2156398,1.0,1.0,1.0,1.0,1.0,0.0038499999999999,-0.011917400
2156399,1.0,1.0,1.0,1.0,1.0,0.0000000000000000,-0.011437500

In [28]:
compressed_pickle('training_set_normalized_features', training_set)

In [29]:
testing_set = decompress_pickle('testing_set.pbz2')
testing_set

,Theta,Pitch,Duty Cycle,Fill Factor,Mode,Lambda,Transmission
0,10.0,0.0000005,0.4,0.2,0,0.00000170000,-0.0000150191
1,10.0,0.0000005,0.4,0.2,0,0.00000169738,-0.0000232995
2,10.0,0.0000005,0.4,0.2,0,0.00000169476,-0.0000328789
3,10.0,0.0000005,0.4,0.2,0,0.00000169215,-0.0000431445
4,10.0,0.0000005,0.4,0.2,0,0.00000168955,-0.0000535258
...,...,...,...,...,...,...,...
102395,20.0,0.0000015,0.8,0.6,1,0.00000130618,-0.0126465000
102396,20.0,0.0000015,0.8,0.6,1,0.00000130463,-0.0123096000
102397,20.0,0.0000015,0.8,0.6,1,0.00000130308,-0.0121443000
102398,20.0,0.0000015,0.8,0.6,1,0.00000130154,-0.0119174000
102399,20.0,0.0000015,0.8,0.6,1,0.00000130000,-0.0114375000

In [31]:
columns_to_norm = ['Theta', 'Pitch', 'Duty Cycle', 'Fill Factor', 'Mode', 'Lambda']
testing_set[columns_to_norm] = testing_set[columns_to_norm].apply(lambda x: (x-x.min()) / (x.max() - x.min()))
testing_set

,Theta,Pitch,Duty Cycle,Fill Factor,Mode,Lambda,Transmission
0,0.0,0.0,0.0,0.0,0.0,1.0000000000000000,-0.0000150191
1,0.0,0.0,0.0,0.0,0.0,0.9934499999999997,-0.0000232995
2,0.0,0.0,0.0,0.0,0.0,0.9869000000000000,-0.0000328789
3,0.0,0.0,0.0,0.0,0.0,0.9803749999999999,-0.0000431445
4,0.0,0.0,0.0,0.0,0.0,0.9738749999999999,-0.0000535258
...,...,...,...,...,...,...,...
102395,1.0,1.0,1.0,1.0,1.0,0.0154499999999998,-0.0126465000
102396,1.0,1.0,1.0,1.0,1.0,0.0115749999999998,-0.0123096000
102397,1.0,1.0,1.0,1.0,1.0,0.0076999999999997,-0.0121443000
102398,1.0,1.0,1.0,1.0,1.0,0.0038499999999999,-0.0119174000
102399,1.0,1.0,1.0,1.0,1.0,0.0000000000000000,-0.0114375000

In [32]:
compressed_pickle('testing_set_normalized_features', testing_set)