In [4]:
import torch
from torch import nn
import numpy as np
import pandas
from torch.utils.data import Dataset, DataLoader
import time

pandas.set_option('precision', 20)

In [5]:
def get_features(dataframe:pandas.DataFrame)->torch.Tensor:
        return dataframe[["Theta", "Pitch", "Duty Cycle", "Fill Factor", "Lambda", "Mode"]].values

In [26]:
dataset = pandas.read_csv('DATA_FILES/dataset_new.csv')
dataset

,Theta,Pitch,Duty Cycle,Fill Factor,Mode,Lambda,Transmission
0,5.0,0.00000050,0.4000000000000000222,0.2000000000000000111,0,0.00000170,0.00009679999999999999
1,5.0,0.00000050,0.4000000000000000222,0.2000000000000000111,0,0.00000170,0.00009790000000000001
2,5.0,0.00000050,0.4000000000000000222,0.2000000000000000111,0,0.00000169,0.00009970000000000000
3,5.0,0.00000050,0.4000000000000000222,0.2000000000000000111,0,0.00000169,0.00010178900000000000
4,5.0,0.00000050,0.4000000000000000222,0.2000000000000000111,0,0.00000169,0.00010362100000000000
...,...,...,...,...,...,...,...
522395,15.0,0.00000075,0.6500000000000000222,0.2500000000000000000,1,0.00000131,-0.00056732500000000003
522396,15.0,0.00000075,0.6500000000000000222,0.2500000000000000000,1,0.00000130,-0.00057533699999999998
522397,15.0,0.00000075,0.6500000000000000222,0.2500000000000000000,1,0.00000130,-0.00058150900000000002
522398,15.0,0.00000075,0.6500000000000000222,0.2500000000000000000,1,0.00000130,-0.00058426099999999998
522399,15.0,0.00000075,0.6500000000000000222,0.2500000000000000000,1,0.00000130,-0.00058285900000000002

In [27]:
new_data = pandas.read_csv('DATA_FILES/output_data_11_03_22.csv')
new_data

,Theta,Pitch,Duty Cycle,Fill Factor,Mode,Lambda,Transmission
0,8.0,0.000000886,0.80000000000000004441,0.5999999999999999778,0,0.00000170,0.02297930000000000111
1,8.0,0.000000886,0.80000000000000004441,0.5999999999999999778,0,0.00000170,0.02016240000000000393
2,8.0,0.000000886,0.80000000000000004441,0.5999999999999999778,0,0.00000169,0.01755320000000000144
3,8.0,0.000000886,0.80000000000000004441,0.5999999999999999778,0,0.00000169,0.01513450000000000038
4,8.0,0.000000886,0.80000000000000004441,0.5999999999999999778,0,0.00000169,0.01289850000000000198
...,...,...,...,...,...,...,...
39995,9.0,0.000000886,0.80000000000000004441,0.5999999999999999778,1,0.00000131,-0.00007559999999999999
39996,9.0,0.000000886,0.80000000000000004441,0.5999999999999999778,1,0.00000130,-0.00008200000000000000
39997,9.0,0.000000886,0.80000000000000004441,0.5999999999999999778,1,0.00000130,-0.00008990000000000000
39998,9.0,0.000000886,0.80000000000000004441,0.5999999999999999778,1,0.00000130,-0.00009970000000000000
39999,9.0,0.000000886,0.80000000000000004441,0.5999999999999999778,1,0.00000130,-0.00011164800000000000

In [28]:
dataset = dataset.append(new_data)
dataset

,Theta,Pitch,Duty Cycle,Fill Factor,Mode,Lambda,Transmission
0,5.0,0.000000500,0.40000000000000002220,0.2000000000000000111,0,0.00000170,0.00009679999999999999
1,5.0,0.000000500,0.40000000000000002220,0.2000000000000000111,0,0.00000170,0.00009790000000000001
2,5.0,0.000000500,0.40000000000000002220,0.2000000000000000111,0,0.00000169,0.00009970000000000000
3,5.0,0.000000500,0.40000000000000002220,0.2000000000000000111,0,0.00000169,0.00010178900000000000
4,5.0,0.000000500,0.40000000000000002220,0.2000000000000000111,0,0.00000169,0.00010362100000000000
...,...,...,...,...,...,...,...
39995,9.0,0.000000886,0.80000000000000004441,0.5999999999999999778,1,0.00000131,-0.00007559999999999999
39996,9.0,0.000000886,0.80000000000000004441,0.5999999999999999778,1,0.00000130,-0.00008200000000000000
39997,9.0,0.000000886,0.80000000000000004441,0.5999999999999999778,1,0.00000130,-0.00008990000000000000
39998,9.0,0.000000886,0.80000000000000004441,0.5999999999999999778,1,0.00000130,-0.00009970000000000000
39999,9.0,0.000000886,0.80000000000000004441,0.5999999999999999778,1,0.00000130,-0.00011164800000000000

In [29]:
dataset.to_csv('DATA_FILES/dataset_new.csv')

In [30]:
columns_to_norm = ['Theta', 'Pitch', 'Duty Cycle', 'Fill Factor', 'Lambda', 'Mode']
dataset[columns_to_norm] = dataset[columns_to_norm].apply(lambda x: (x-x.min()) / (x.max() - x.min()))
dataset

,Theta,Pitch,Duty Cycle,Fill Factor,Mode,Lambda,Transmission
0,0.00000000000000000000,0.00000000000000000000,0.0,0.0,0.0,1.00000000000000000000,0.00009679999999999999
1,0.00000000000000000000,0.00000000000000000000,0.0,0.0,0.0,1.00000000000000000000,0.00009790000000000001
2,0.00000000000000000000,0.00000000000000000000,0.0,0.0,0.0,0.97499999999999975575,0.00009970000000000000
3,0.00000000000000000000,0.00000000000000000000,0.0,0.0,0.0,0.97499999999999975575,0.00010178900000000000
4,0.00000000000000000000,0.00000000000000000000,0.0,0.0,0.0,0.97499999999999975575,0.00010362100000000000
...,...,...,...,...,...,...,...
39995,0.26666666666666666297,0.38599999999999989875,1.0,1.0,1.0,0.02499999999999976200,-0.00007559999999999999
39996,0.26666666666666666297,0.38599999999999989875,1.0,1.0,1.0,0.00000000000000000000,-0.00008200000000000000
39997,0.26666666666666666297,0.38599999999999989875,1.0,1.0,1.0,0.00000000000000000000,-0.00008990000000000000
39998,0.26666666666666666297,0.38599999999999989875,1.0,1.0,1.0,0.00000000000000000000,-0.00009970000000000000
39999,0.26666666666666666297,0.38599999999999989875,1.0,1.0,1.0,0.00000000000000000000,-0.00011164800000000000

In [31]:
dataset.to_csv('DATA_FILES/dataset_new_min_max_normalized.csv')

In [32]:
training_set = dataset.sample(frac = 0.85)
training_set

,Theta,Pitch,Duty Cycle,Fill Factor,Mode,Lambda,Transmission
514262,1.00000000000000000000,1.00000000000000000000,0.79999999999999982236,0.20000000000000006661,1.0,0.62499999999999988898,-0.00454627999999999977
328190,0.59999999999999997780,0.79999999999999993339,0.79999999999999982236,0.80000000000000004441,0.0,0.03499999999999998251,0.00003900000000000000
349151,0.80000000000000004441,0.00000000000000000000,0.19999999999999990008,0.39999999999999996669,1.0,0.19999999999999967804,-0.00057665099999999996
276867,0.59999999999999997780,0.19999999999999995559,0.19999999999999990008,0.39999999999999996669,0.0,0.60000000000000008882,0.00273312999999999985
3524,0.00000000000000000000,0.00000000000000000000,0.19999999999999990008,0.39999999999999996669,1.0,0.32500000000000006661,-0.00033415499999999999
...,...,...,...,...,...,...,...
376320,0.80000000000000004441,0.40000000000000002220,0.00000000000000000000,0.80000000000000004441,1.0,0.32500000000000006661,-0.00058507699999999993
73526,0.00000000000000000000,1.00000000000000000000,0.00000000000000000000,0.59999999999999997780,1.0,0.29999999999999976685,-0.00243574000000000004
43426,0.00000000000000000000,0.59999999999999997780,0.00000000000000000000,0.00000000000000000000,1.0,0.82500000000000006661,-0.00011808200000000001
199795,0.40000000000000002220,0.19999999999999995559,1.00000000000000000000,0.20000000000000006661,0.0,0.02499999999999976200,0.00025807800000000002
335642,0.59999999999999997780,1.00000000000000000000,0.19999999999999990008,1.00000000000000000000,0.0,0.74999999999999977796,0.22517499999999998628

In [33]:
training_set.to_csv('DATA_FILES/training_set.csv')

In [34]:
testing_set = dataset.drop(training_set.index)
testing_set

,Theta,Pitch,Duty Cycle,Fill Factor,Mode,Lambda,Transmission
50,0.00000000000000000000,0.00000000000000000000,0.0,0.0,0.0,0.69500000000000039524,0.00009109999999999999
71,0.00000000000000000000,0.00000000000000000000,0.0,0.0,0.0,0.57499999999999984457,0.00032632199999999998
156,0.00000000000000000000,0.00000000000000000000,0.0,0.0,0.0,0.17499999999999993339,0.00091295600000000003
213,0.00000000000000000000,0.00000000000000000000,0.0,0.0,1.0,0.92500000000000015543,-0.00055334199999999996
220,0.00000000000000000000,0.00000000000000000000,0.0,0.0,1.0,0.87249999999999994227,-0.00041056000000000003
...,...,...,...,...,...,...,...
39808,0.26666666666666666297,0.38599999999999989875,1.0,1.0,1.0,0.94999999999999995559,-0.00013100800000000000
39815,0.26666666666666666297,0.38599999999999989875,1.0,1.0,1.0,0.89999999999999991118,-0.00013825299999999999
39832,0.26666666666666666297,0.38599999999999989875,1.0,1.0,1.0,0.79999999999999982236,-0.00009899999999999999
39925,0.26666666666666666297,0.38599999999999989875,1.0,1.0,1.0,0.29999999999999976685,-0.00009379999999999999
39996,0.26666666666666666297,0.38599999999999989875,1.0,1.0,1.0,0.00000000000000000000,-0.00008200000000000000

In [35]:
testing_set.to_csv('DATA_FILES/testing_set.csv')