In [4]:
import torch
from torch import nn
import numpy as np
import pandas
from torch.utils.data import Dataset, DataLoader
import time

pandas.set_option('precision', 20)

In [5]:
def get_features(dataframe:pandas.DataFrame)->torch.Tensor:
        return dataframe[["Theta", "Pitch", "Duty Cycle", "Fill Factor", "Lambda", "Mode"]].values

In [11]:
dataset = pandas.read_csv('DATA_FILES/dataset_new.csv')
dataset

,Theta,Pitch,Duty Cycle,Fill Factor,Mode,Lambda,Transmission
0,5.0,0.00000050,0.4000000000000000222,0.2000000000000000111,0,0.00000170,0.00009679999999999999
1,5.0,0.00000050,0.4000000000000000222,0.2000000000000000111,0,0.00000170,0.00009790000000000001
2,5.0,0.00000050,0.4000000000000000222,0.2000000000000000111,0,0.00000169,0.00009970000000000000
3,5.0,0.00000050,0.4000000000000000222,0.2000000000000000111,0,0.00000169,0.00010178900000000000
4,5.0,0.00000050,0.4000000000000000222,0.2000000000000000111,0,0.00000169,0.00010362100000000000
...,...,...,...,...,...,...,...
522395,15.0,0.00000075,0.6500000000000000222,0.2500000000000000000,1,0.00000131,-0.00056732500000000003
522396,15.0,0.00000075,0.6500000000000000222,0.2500000000000000000,1,0.00000130,-0.00057533699999999998
522397,15.0,0.00000075,0.6500000000000000222,0.2500000000000000000,1,0.00000130,-0.00058150900000000002
522398,15.0,0.00000075,0.6500000000000000222,0.2500000000000000000,1,0.00000130,-0.00058426099999999998
522399,15.0,0.00000075,0.6500000000000000222,0.2500000000000000000,1,0.00000130,-0.00058285900000000002

In [12]:
columns_to_norm = ['Theta', 'Pitch', 'Duty Cycle', 'Fill Factor', 'Lambda', 'Mode']
dataset[columns_to_norm] = dataset[columns_to_norm].apply(lambda x: (x-x.min()) / (x.max() - x.min()))
dataset

,Theta,Pitch,Duty Cycle,Fill Factor,Mode,Lambda,Transmission
0,0.00000000000000000000,0.00,0.000,0.00000000000000000000,0.0,1.00000000000000000000,0.00009679999999999999
1,0.00000000000000000000,0.00,0.000,0.00000000000000000000,0.0,1.00000000000000000000,0.00009790000000000001
2,0.00000000000000000000,0.00,0.000,0.00000000000000000000,0.0,0.97499999999999975575,0.00009970000000000000
3,0.00000000000000000000,0.00,0.000,0.00000000000000000000,0.0,0.97499999999999975575,0.00010178900000000000
4,0.00000000000000000000,0.00,0.000,0.00000000000000000000,0.0,0.97499999999999975575,0.00010362100000000000
...,...,...,...,...,...,...,...
522395,0.66666666666666662966,0.25,0.625,0.12499999999999998612,1.0,0.02499999999999976200,-0.00056732500000000003
522396,0.66666666666666662966,0.25,0.625,0.12499999999999998612,1.0,0.00000000000000000000,-0.00057533699999999998
522397,0.66666666666666662966,0.25,0.625,0.12499999999999998612,1.0,0.00000000000000000000,-0.00058150900000000002
522398,0.66666666666666662966,0.25,0.625,0.12499999999999998612,1.0,0.00000000000000000000,-0.00058426099999999998
522399,0.66666666666666662966,0.25,0.625,0.12499999999999998612,1.0,0.00000000000000000000,-0.00058285900000000002

In [13]:
dataset.to_csv('DATA_FILES/dataset_new_min_max_normalized.csv')

In [14]:
training_set = dataset.sample(frac = 0.85)
training_set

,Theta,Pitch,Duty Cycle,Fill Factor,Mode,Lambda,Transmission
454339,1.00000000000000000000,0.19999999999999995559,0.59999999999999997780,0.20000000000000006661,1.0,0.24999999999999972244,-0.14183299999999998686
388739,0.80000000000000004441,0.40000000000000002220,1.00000000000000000000,1.00000000000000000000,1.0,0.24999999999999972244,-0.00019870200000000001
293951,0.59999999999999997780,0.40000000000000002220,0.40000000000000007772,0.39999999999999996669,1.0,0.19999999999999967804,-0.00018230000000000001
171436,0.20000000000000001110,1.00000000000000000000,1.00000000000000000000,0.39999999999999996669,1.0,0.77500000000000002220,-0.00510924000000000014
211986,0.40000000000000002220,0.40000000000000002220,0.79999999999999982236,0.20000000000000006661,1.0,0.05000000000000005135,-0.00034877500000000001
...,...,...,...,...,...,...,...
166254,0.20000000000000001110,1.00000000000000000000,0.59999999999999997780,0.20000000000000006661,1.0,0.67250000000000020872,-0.01843170000000000225
419036,0.80000000000000004441,1.00000000000000000000,0.00000000000000000000,0.59999999999999997780,1.0,0.77500000000000002220,-0.00354134000000000003
506992,1.00000000000000000000,1.00000000000000000000,0.19999999999999990008,0.20000000000000006661,0.0,0.02499999999999976200,0.00024021000000000001
455835,1.00000000000000000000,0.19999999999999995559,0.59999999999999997780,1.00000000000000000000,1.0,0.77500000000000002220,-0.00114160999999999993
170837,0.20000000000000001110,1.00000000000000000000,1.00000000000000000000,0.20000000000000006661,0.0,0.77000000000000012879,0.02841870000000000160

In [15]:
training_set.to_csv('DATA_FILES/training_set.csv')

In [16]:
testing_set = dataset.drop(training_set.index)
testing_set

,Theta,Pitch,Duty Cycle,Fill Factor,Mode,Lambda,Transmission
3,0.00000000000000000000,0.00,0.000,0.00000000000000000000,0.0,0.97499999999999975575,0.00010178900000000000
4,0.00000000000000000000,0.00,0.000,0.00000000000000000000,0.0,0.97499999999999975575,0.00010362100000000000
6,0.00000000000000000000,0.00,0.000,0.00000000000000000000,0.0,0.94999999999999995559,0.00010457700000000001
13,0.00000000000000000000,0.00,0.000,0.00000000000000000000,0.0,0.92500000000000015543,0.00005290000000000001
16,0.00000000000000000000,0.00,0.000,0.00000000000000000000,0.0,0.89750000000000018652,0.00001880000000000000
...,...,...,...,...,...,...,...
522328,0.66666666666666662966,0.25,0.625,0.12499999999999998612,1.0,0.29999999999999976685,-0.00196127000000000020
522338,0.66666666666666662966,0.25,0.625,0.12499999999999998612,1.0,0.24999999999999972244,-0.00102702999999999996
522361,0.66666666666666662966,0.25,0.625,0.12499999999999998612,1.0,0.14999999999999963363,-0.00113557999999999997
522380,0.66666666666666662966,0.25,0.625,0.12499999999999998612,1.0,0.07499999999999981681,-0.00049712400000000005
522393,0.66666666666666662966,0.25,0.625,0.12499999999999998612,1.0,0.02499999999999976200,-0.00055367699999999992

In [17]:
testing_set.to_csv('DATA_FILES/testing_set.csv')