In [4]:
import torch
from torch import nn
import numpy as np
import pandas
from torch.utils.data import Dataset, DataLoader
import time

pandas.set_option('precision', 20)

In [5]:
def get_features(dataframe:pandas.DataFrame)->torch.Tensor:
        return dataframe[["Theta", "Pitch", "Duty Cycle", "Fill Factor", "Lambda", "Mode"]].values

In [46]:
dataset = pandas.read_csv('DATA_FILES/dataset_new_neglect.csv')
dataset

FileNotFoundError: [Errno 2] No such file or directory: 'DATA_FILES/dataset_new_neglect.csv.csv'

In [37]:
new_data = pandas.read_csv('DATA_FILES/output_data_13_03_22.csv')
new_data

,Fill Factor,Pitch,Duty Cycle,Theta,Mode,Lambda,Transmission
0,10.0,0.00000151,0.44444399999999995021,0.55555600000000004979,0,0.00000170000,-0.00016305899999999998
1,10.0,0.00000151,0.44444399999999995021,0.55555600000000004979,0,0.00000169738,-0.00015550800000000000
2,10.0,0.00000151,0.44444399999999995021,0.55555600000000004979,0,0.00000169476,-0.00014162499999999999
3,10.0,0.00000151,0.44444399999999995021,0.55555600000000004979,0,0.00000169215,-0.00012065900000000000
4,10.0,0.00000151,0.44444399999999995021,0.55555600000000004979,0,0.00000168955,-0.00009237620000000001
...,...,...,...,...,...,...,...
39995,11.0,0.00000151,0.44444399999999995021,0.55555600000000004979,1,0.00000130618,-0.00080868699999999999
39996,11.0,0.00000151,0.44444399999999995021,0.55555600000000004979,1,0.00000130463,-0.00084836399999999989
39997,11.0,0.00000151,0.44444399999999995021,0.55555600000000004979,1,0.00000130308,-0.00088449199999999996
39998,11.0,0.00000151,0.44444399999999995021,0.55555600000000004979,1,0.00000130154,-0.00094034800000000003
39999,11.0,0.00000151,0.44444399999999995021,0.55555600000000004979,1,0.00000130000,-0.00100734000000000001

In [38]:
dataset = dataset.append(new_data)
dataset

,Unnamed: 0,Theta,Pitch,Duty Cycle,Fill Factor,Mode,Lambda,Transmission
0,0.0,5.00000000000000000000,0.00000050,0.40000000000000002220,0.2000000000000000111,0,0.00000170000,0.00009679999999999999
1,1.0,5.00000000000000000000,0.00000050,0.40000000000000002220,0.2000000000000000111,0,0.00000170000,0.00009789999999999999
2,2.0,5.00000000000000000000,0.00000050,0.40000000000000002220,0.2000000000000000111,0,0.00000169000,0.00009970000000000000
3,3.0,5.00000000000000000000,0.00000050,0.40000000000000002220,0.2000000000000000111,0,0.00000169000,0.00010178900000000000
4,4.0,5.00000000000000000000,0.00000050,0.40000000000000002220,0.2000000000000000111,0,0.00000169000,0.00010362100000000000
...,...,...,...,...,...,...,...,...
39995,NaN,0.55555600000000004979,0.00000151,0.44444399999999995021,11.0000000000000000000,1,0.00000130618,-0.00080868699999999999
39996,NaN,0.55555600000000004979,0.00000151,0.44444399999999995021,11.0000000000000000000,1,0.00000130463,-0.00084836399999999989
39997,NaN,0.55555600000000004979,0.00000151,0.44444399999999995021,11.0000000000000000000,1,0.00000130308,-0.00088449199999999996
39998,NaN,0.55555600000000004979,0.00000151,0.44444399999999995021,11.0000000000000000000,1,0.00000130154,-0.00094034800000000003
39999,NaN,0.55555600000000004979,0.00000151,0.44444399999999995021,11.0000000000000000000,1,0.00000130000,-0.00100734000000000001

In [39]:
dataset.to_csv('DATA_FILES/dataset_new.csv')

In [40]:
columns_to_norm = ['Theta', 'Pitch', 'Duty Cycle', 'Fill Factor', 'Lambda', 'Mode']
dataset[columns_to_norm] = dataset[columns_to_norm].apply(lambda x: (x-x.min()) / (x.max() - x.min()))
dataset

,Unnamed: 0,Theta,Pitch,Duty Cycle,Fill Factor,Mode,Lambda,Transmission
0,0.0,0.22857141093877508808,0.0,0.00000000000000000000,0.0,0.0,1.00000000000000000000,0.00009679999999999999
1,1.0,0.22857141093877508808,0.0,0.00000000000000000000,0.0,0.0,1.00000000000000000000,0.00009789999999999999
2,2.0,0.22857141093877508808,0.0,0.00000000000000000000,0.0,0.0,0.97499999999999975575,0.00009970000000000000
3,3.0,0.22857141093877508808,0.0,0.00000000000000000000,0.0,0.0,0.97499999999999975575,0.00010178900000000000
4,4.0,0.22857141093877508808,0.0,0.00000000000000000000,0.0,0.0,0.97499999999999975575,0.00010362100000000000
...,...,...,...,...,...,...,...,...
39995,NaN,0.00000000000000000000,1.0,0.11110999999999982002,1.0,1.0,0.01544999999999978509,-0.00080868699999999999
39996,NaN,0.00000000000000000000,1.0,0.11110999999999982002,1.0,1.0,0.01157499999999975909,-0.00084836399999999989
39997,NaN,0.00000000000000000000,1.0,0.11110999999999982002,1.0,1.0,0.00769999999999973223,-0.00088449199999999996
39998,NaN,0.00000000000000000000,1.0,0.11110999999999982002,1.0,1.0,0.00384999999999986612,-0.00094034800000000003
39999,NaN,0.00000000000000000000,1.0,0.11110999999999982002,1.0,1.0,0.00000000000000000000,-0.00100734000000000001

In [41]:
dataset.to_csv('DATA_FILES/dataset_new_min_max_normalized.csv')

In [42]:
training_set = dataset.sample(frac = 0.85)
training_set

,Unnamed: 0,Theta,Pitch,Duty Cycle,Fill Factor,Mode,Lambda,Transmission
91880,91880.0,0.38285712875102007047,0.00000000000000000000,0.40000000000000007772,0.00740740740740740856,1.0,0.52499999999999980016,-0.00018621600000000001
155701,155701.0,0.38285712875102007047,0.79207920792079211658,0.79999999999999982236,0.03703703703703703498,0.0,0.42499999999999965583,0.01701120000000000063
396973,396973.0,0.84571428218775501762,0.59405940594059414295,0.59999999999999997780,0.01481481481481481191,0.0,0.10000000000000010270,0.02824979999999999852
305792,305792.0,0.69142856437551003523,0.59405940594059414295,0.19999999999999990008,0.01481481481481481191,0.0,0.02499999999999976200,0.00719532999999999978
127667,127667.0,0.38285712875102007047,0.39603960396039622482,1.00000000000000000000,0.00740740740740740856,0.0,0.60000000000000008882,0.00224220000000000018
...,...,...,...,...,...,...,...,...
482593,482593.0,1.00000000000000000000,0.59405940594059414295,0.59999999999999997780,0.00000000000000000000,0.0,0.02499999999999976200,0.00966889999999999937
491592,491592.0,1.00000000000000000000,0.79207920792079211658,0.00000000000000000000,0.02962962962962962729,1.0,0.02499999999999976200,-0.00329527999999999982
512332,512332.0,1.00000000000000000000,0.99009900990099020124,0.59999999999999997780,0.01481481481481481191,1.0,0.27500000000000002220,-0.04434140000000000303
245016,245016.0,0.53714284656326505285,0.99009900990099020124,0.00000000000000000000,0.00000000000000000000,1.0,0.89749999999999974243,-0.02609030000000000030
345347,345347.0,0.69142856437551003523,0.99009900990099020124,1.00000000000000000000,0.03703703703703703498,0.0,0.22499999999999997780,0.00295650999999999987

In [43]:
training_set.to_csv('DATA_FILES/training_set.csv')

In [44]:
testing_set = dataset.drop(training_set.index)
testing_set

,Unnamed: 0,Theta,Pitch,Duty Cycle,Fill Factor,Mode,Lambda,Transmission
70,70.0,0.22857141093877508808,0.0,0.00000000000000000000,0.0,0.0,0.58500000000000007550,0.00026151899999999999
174,174.0,0.22857141093877508808,0.0,0.00000000000000000000,0.0,0.0,0.10000000000000010270,0.00006442800000000000
222,222.0,0.22857141093877508808,0.0,0.00000000000000000000,0.0,1.0,0.84999999999999986677,-0.00035881400000000000
231,231.0,0.22857141093877508808,0.0,0.00000000000000000000,0.0,1.0,0.79999999999999982236,-0.00022971299999999999
256,256.0,0.22857141093877508808,0.0,0.00000000000000000000,0.0,1.0,0.65000000000000013323,-0.00018530400000000001
...,...,...,...,...,...,...,...,...
39640,NaN,0.00000000000000000000,1.0,0.11110999999999982002,1.0,0.0,0.75244999999999961915,0.12040399999999999714
39777,NaN,0.00000000000000000000,1.0,0.11110999999999982002,1.0,0.0,0.08679999999999996052,0.00823317999999999967
39880,NaN,0.00000000000000000000,1.0,0.11110999999999982002,1.0,1.0,0.53217499999999984261,-0.00254866999999999984
39980,NaN,0.00000000000000000000,1.0,0.11110999999999982002,1.0,1.0,0.07470000000000000251,-0.00093938899999999989
39996,NaN,0.00000000000000000000,1.0,0.11110999999999982002,1.0,1.0,0.01157499999999975909,-0.00084836399999999989

In [45]:
testing_set.to_csv('DATA_FILES/testing_set.csv')